version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "07:00"
  allow:
      - dependency-type: "direct" # Optional: Focus on direct dependencies
      - update-types: ["security"]
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
      - dependency-name: "csv-parse" 
      - dependency-name: "globby" 
      - dependency-name: "madge"  
      - dependency-name: "mocha"
      - dependency-name: "nyc"
      - dependency-name: "@oclif/*"    
      - dependency-name: "soql-parser-js" 
      - dependency-name: "@babel/*"  