version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "7:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
      - dependency-name: "csv-parse" 
      - dependency-name: "globby" 
        