name: Stale Issues
on:
  schedule:
    - cron: "30 1 * * *"

jobs:
  close-stale-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v6.0.1
        with:
          days-before-issue-stale: 3
          days-before-issue-close: 0
          stale-issue-label: "to-close"
          any-of-labels: "bug,help-wanted,gui,wontfix,roadmap,non-reproducable"
          exempt-issue-labels: "in-progress"
          stale-issue-message: "-> Hello!<br />Thank you for using the SFDMU.<br />This case has been closed, since it had no activity for the last 3 days."
          repo-token: ${{ secrets.GITHUB_TOKEN }}

  close-completed-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v6.0.1
        with:
          days-before-issue-stale: 3
          days-before-issue-close: 0
          any-of-labels: "completed"
          stale-issue-label: "to-close"
          close-issue-reason: "completed"
          stale-issue-message: "-> Hello!<br />Thank you for using the SFDMU.<br /> This case has been closed, since it has been marked as completed and had no activity for the last 3 days."
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          
