name: Treat Stale Issues
on:
  schedule:
    - cron: "30 1 * * *"

jobs:
  close-stale-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v6.0.1
        with:
          days-before-issue-stale: 3
          days-before-issue-close: 3
          stale-issue-label: "stale"
          close-issue-label: "closed-inactive"
          any-of-labels: "bug,help-wanted,gui"
          exempt-issue-labels: "in-progress"
          stale-issue-message: "-> This issue is marked as *stale* because it had any activity for the last 3 days. <br /> It will be closed after another 3 days of inactivity."
          close-issue-message: "-> This issue was closed because it has been inactive for 3 days since being marked as stale."
          repo-token: ${{ secrets.GITHUB_TOKEN }}

  close-completed-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v6.0.1
        with:
          days-before-issue-stale: 0
          days-before-issue-close: 0
          stale-issue-label: "to-close"
          close-issue-label: "closed"
          any-of-labels: "completed"
          stale-issue-message: "-> This issue is closed because it has been already marked as completed(fixed), but had no activity for the last 3 days."
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          
  close-wontfix-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v6.0.1
        with:
          days-before-issue-stale: 0
          days-before-issue-close: 0
          stale-issue-label: "to-close"
          close-issue-label: "closed"
          any-of-labels: "wontfix"
          stale-issue-message: "-> After the deep investigation of this issue, we have decided that we will not release this fix/feature in the nearest feature.<br />It's still possible, that we will re-evaluate our desicion again later.<br />For now, the issue has been closed."
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          
  close-roadmap-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v6.0.1
        with:
          days-before-issue-stale: 0
          days-before-issue-close: 0
          stale-issue-label: "to-close"
          close-issue-label: "closed"
          any-of-labels: "roadmap"
          stale-issue-message: "-> This issue/feature request is included in our Roadmap and will be scheduled for one of our future releases.<br />For now, the issue has been closed."
          repo-token: ${{ secrets.GITHUB_TOKEN }}

  close-non-reproducable-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v6.0.1
        with:
          days-before-issue-stale: 0
          days-before-issue-close: 0
          stale-issue-label: "to-close"
          close-issue-label: "closed"
          any-of-labels: "non-reproducable"
          stale-issue-message: "-> Unfortunately, we could not reproduce this issue on our end. It's possible that need to debug directly on your local machine.<br />Please, take a look on the [How to Debug the SFDMU locally](https://help.sfdmu.com/plugin-basics/basic-usage/debugging).<br />The issue has been closed."
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          

